Repository fior-app/web, pull requests merged in 2020-10, with the labels that each got.

#94 Style/project
  src/screens/mentorspaces/mentorspace_details/project/GithubLink.js
  src/screens/mentorspaces/mentorspace_details/project/GithubRepositories.js
  src/screens/mentorspaces/mentorspace_details/project/ProjectWidget.js
Labels: hacktoberfest

#102 add recent post
  src/screens/question/forum/recent_forum.js
  src/screens/question/forum/recent_post.js
Labels: hacktoberfest-accepted

#103 edit post
  src/screens/question/forum/edit_post.js
Labels: hacktoberfest, hacktoberfest-accepted

#104 question viewing types
  src/screens/question/view_type/auth.js
  src/screens/question/view_type/reduce.js
  src/screens/question/view_type/view.js
Labels: hacktoberfest, hacktoberfest-accepted

#105 viewing single question update
  src/screens/question/view_type/auth.js
  src/screens/question/view_type/reduce.js
  src/screens/question/view_type/single_view.js
Labels: hacktoberfest, hacktoberfest-accepted
